// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dynamicequity/service.proto

package dynamicequity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignInRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{0}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

type SignInResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{1}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

type SignOutRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutRequest) Reset()         { *m = SignOutRequest{} }
func (m *SignOutRequest) String() string { return proto.CompactTextString(m) }
func (*SignOutRequest) ProtoMessage()    {}
func (*SignOutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{2}
}

func (m *SignOutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutRequest.Unmarshal(m, b)
}
func (m *SignOutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutRequest.Marshal(b, m, deterministic)
}
func (m *SignOutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutRequest.Merge(m, src)
}
func (m *SignOutRequest) XXX_Size() int {
	return xxx_messageInfo_SignOutRequest.Size(m)
}
func (m *SignOutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutRequest proto.InternalMessageInfo

type SignOutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignOutResponse) Reset()         { *m = SignOutResponse{} }
func (m *SignOutResponse) String() string { return proto.CompactTextString(m) }
func (*SignOutResponse) ProtoMessage()    {}
func (*SignOutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{3}
}

func (m *SignOutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignOutResponse.Unmarshal(m, b)
}
func (m *SignOutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignOutResponse.Marshal(b, m, deterministic)
}
func (m *SignOutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignOutResponse.Merge(m, src)
}
func (m *SignOutResponse) XXX_Size() int {
	return xxx_messageInfo_SignOutResponse.Size(m)
}
func (m *SignOutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignOutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignOutResponse proto.InternalMessageInfo

type SignUpRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{4}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

type SignUpResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{5}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

type PieListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieListRequest) Reset()         { *m = PieListRequest{} }
func (m *PieListRequest) String() string { return proto.CompactTextString(m) }
func (*PieListRequest) ProtoMessage()    {}
func (*PieListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{6}
}

func (m *PieListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieListRequest.Unmarshal(m, b)
}
func (m *PieListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieListRequest.Marshal(b, m, deterministic)
}
func (m *PieListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieListRequest.Merge(m, src)
}
func (m *PieListRequest) XXX_Size() int {
	return xxx_messageInfo_PieListRequest.Size(m)
}
func (m *PieListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PieListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PieListRequest proto.InternalMessageInfo

type PieListResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieListResponse) Reset()         { *m = PieListResponse{} }
func (m *PieListResponse) String() string { return proto.CompactTextString(m) }
func (*PieListResponse) ProtoMessage()    {}
func (*PieListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{7}
}

func (m *PieListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieListResponse.Unmarshal(m, b)
}
func (m *PieListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieListResponse.Marshal(b, m, deterministic)
}
func (m *PieListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieListResponse.Merge(m, src)
}
func (m *PieListResponse) XXX_Size() int {
	return xxx_messageInfo_PieListResponse.Size(m)
}
func (m *PieListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PieListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PieListResponse proto.InternalMessageInfo

type PieCreateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieCreateRequest) Reset()         { *m = PieCreateRequest{} }
func (m *PieCreateRequest) String() string { return proto.CompactTextString(m) }
func (*PieCreateRequest) ProtoMessage()    {}
func (*PieCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{8}
}

func (m *PieCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieCreateRequest.Unmarshal(m, b)
}
func (m *PieCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieCreateRequest.Marshal(b, m, deterministic)
}
func (m *PieCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieCreateRequest.Merge(m, src)
}
func (m *PieCreateRequest) XXX_Size() int {
	return xxx_messageInfo_PieCreateRequest.Size(m)
}
func (m *PieCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PieCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PieCreateRequest proto.InternalMessageInfo

type PieCreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieCreateResponse) Reset()         { *m = PieCreateResponse{} }
func (m *PieCreateResponse) String() string { return proto.CompactTextString(m) }
func (*PieCreateResponse) ProtoMessage()    {}
func (*PieCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{9}
}

func (m *PieCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieCreateResponse.Unmarshal(m, b)
}
func (m *PieCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieCreateResponse.Marshal(b, m, deterministic)
}
func (m *PieCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieCreateResponse.Merge(m, src)
}
func (m *PieCreateResponse) XXX_Size() int {
	return xxx_messageInfo_PieCreateResponse.Size(m)
}
func (m *PieCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PieCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PieCreateResponse proto.InternalMessageInfo

type PieArchiveRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieArchiveRequest) Reset()         { *m = PieArchiveRequest{} }
func (m *PieArchiveRequest) String() string { return proto.CompactTextString(m) }
func (*PieArchiveRequest) ProtoMessage()    {}
func (*PieArchiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{10}
}

func (m *PieArchiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieArchiveRequest.Unmarshal(m, b)
}
func (m *PieArchiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieArchiveRequest.Marshal(b, m, deterministic)
}
func (m *PieArchiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieArchiveRequest.Merge(m, src)
}
func (m *PieArchiveRequest) XXX_Size() int {
	return xxx_messageInfo_PieArchiveRequest.Size(m)
}
func (m *PieArchiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PieArchiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PieArchiveRequest proto.InternalMessageInfo

type PieArchiveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieArchiveResponse) Reset()         { *m = PieArchiveResponse{} }
func (m *PieArchiveResponse) String() string { return proto.CompactTextString(m) }
func (*PieArchiveResponse) ProtoMessage()    {}
func (*PieArchiveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{11}
}

func (m *PieArchiveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieArchiveResponse.Unmarshal(m, b)
}
func (m *PieArchiveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieArchiveResponse.Marshal(b, m, deterministic)
}
func (m *PieArchiveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieArchiveResponse.Merge(m, src)
}
func (m *PieArchiveResponse) XXX_Size() int {
	return xxx_messageInfo_PieArchiveResponse.Size(m)
}
func (m *PieArchiveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PieArchiveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PieArchiveResponse proto.InternalMessageInfo

type PieProjectListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieProjectListRequest) Reset()         { *m = PieProjectListRequest{} }
func (m *PieProjectListRequest) String() string { return proto.CompactTextString(m) }
func (*PieProjectListRequest) ProtoMessage()    {}
func (*PieProjectListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{12}
}

func (m *PieProjectListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieProjectListRequest.Unmarshal(m, b)
}
func (m *PieProjectListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieProjectListRequest.Marshal(b, m, deterministic)
}
func (m *PieProjectListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieProjectListRequest.Merge(m, src)
}
func (m *PieProjectListRequest) XXX_Size() int {
	return xxx_messageInfo_PieProjectListRequest.Size(m)
}
func (m *PieProjectListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PieProjectListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PieProjectListRequest proto.InternalMessageInfo

type PieProjectListResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieProjectListResponse) Reset()         { *m = PieProjectListResponse{} }
func (m *PieProjectListResponse) String() string { return proto.CompactTextString(m) }
func (*PieProjectListResponse) ProtoMessage()    {}
func (*PieProjectListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{13}
}

func (m *PieProjectListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieProjectListResponse.Unmarshal(m, b)
}
func (m *PieProjectListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieProjectListResponse.Marshal(b, m, deterministic)
}
func (m *PieProjectListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieProjectListResponse.Merge(m, src)
}
func (m *PieProjectListResponse) XXX_Size() int {
	return xxx_messageInfo_PieProjectListResponse.Size(m)
}
func (m *PieProjectListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PieProjectListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PieProjectListResponse proto.InternalMessageInfo

type PieProjectAddRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieProjectAddRequest) Reset()         { *m = PieProjectAddRequest{} }
func (m *PieProjectAddRequest) String() string { return proto.CompactTextString(m) }
func (*PieProjectAddRequest) ProtoMessage()    {}
func (*PieProjectAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{14}
}

func (m *PieProjectAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieProjectAddRequest.Unmarshal(m, b)
}
func (m *PieProjectAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieProjectAddRequest.Marshal(b, m, deterministic)
}
func (m *PieProjectAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieProjectAddRequest.Merge(m, src)
}
func (m *PieProjectAddRequest) XXX_Size() int {
	return xxx_messageInfo_PieProjectAddRequest.Size(m)
}
func (m *PieProjectAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PieProjectAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PieProjectAddRequest proto.InternalMessageInfo

type PieProjectAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieProjectAddResponse) Reset()         { *m = PieProjectAddResponse{} }
func (m *PieProjectAddResponse) String() string { return proto.CompactTextString(m) }
func (*PieProjectAddResponse) ProtoMessage()    {}
func (*PieProjectAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{15}
}

func (m *PieProjectAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieProjectAddResponse.Unmarshal(m, b)
}
func (m *PieProjectAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieProjectAddResponse.Marshal(b, m, deterministic)
}
func (m *PieProjectAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieProjectAddResponse.Merge(m, src)
}
func (m *PieProjectAddResponse) XXX_Size() int {
	return xxx_messageInfo_PieProjectAddResponse.Size(m)
}
func (m *PieProjectAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PieProjectAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PieProjectAddResponse proto.InternalMessageInfo

type PieProjectArchiveRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieProjectArchiveRequest) Reset()         { *m = PieProjectArchiveRequest{} }
func (m *PieProjectArchiveRequest) String() string { return proto.CompactTextString(m) }
func (*PieProjectArchiveRequest) ProtoMessage()    {}
func (*PieProjectArchiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{16}
}

func (m *PieProjectArchiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieProjectArchiveRequest.Unmarshal(m, b)
}
func (m *PieProjectArchiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieProjectArchiveRequest.Marshal(b, m, deterministic)
}
func (m *PieProjectArchiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieProjectArchiveRequest.Merge(m, src)
}
func (m *PieProjectArchiveRequest) XXX_Size() int {
	return xxx_messageInfo_PieProjectArchiveRequest.Size(m)
}
func (m *PieProjectArchiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PieProjectArchiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PieProjectArchiveRequest proto.InternalMessageInfo

type PieProjectArchiveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieProjectArchiveResponse) Reset()         { *m = PieProjectArchiveResponse{} }
func (m *PieProjectArchiveResponse) String() string { return proto.CompactTextString(m) }
func (*PieProjectArchiveResponse) ProtoMessage()    {}
func (*PieProjectArchiveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{17}
}

func (m *PieProjectArchiveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieProjectArchiveResponse.Unmarshal(m, b)
}
func (m *PieProjectArchiveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieProjectArchiveResponse.Marshal(b, m, deterministic)
}
func (m *PieProjectArchiveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieProjectArchiveResponse.Merge(m, src)
}
func (m *PieProjectArchiveResponse) XXX_Size() int {
	return xxx_messageInfo_PieProjectArchiveResponse.Size(m)
}
func (m *PieProjectArchiveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PieProjectArchiveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PieProjectArchiveResponse proto.InternalMessageInfo

type PieUserListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieUserListRequest) Reset()         { *m = PieUserListRequest{} }
func (m *PieUserListRequest) String() string { return proto.CompactTextString(m) }
func (*PieUserListRequest) ProtoMessage()    {}
func (*PieUserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{18}
}

func (m *PieUserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieUserListRequest.Unmarshal(m, b)
}
func (m *PieUserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieUserListRequest.Marshal(b, m, deterministic)
}
func (m *PieUserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieUserListRequest.Merge(m, src)
}
func (m *PieUserListRequest) XXX_Size() int {
	return xxx_messageInfo_PieUserListRequest.Size(m)
}
func (m *PieUserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PieUserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PieUserListRequest proto.InternalMessageInfo

type PieUserListResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieUserListResponse) Reset()         { *m = PieUserListResponse{} }
func (m *PieUserListResponse) String() string { return proto.CompactTextString(m) }
func (*PieUserListResponse) ProtoMessage()    {}
func (*PieUserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{19}
}

func (m *PieUserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieUserListResponse.Unmarshal(m, b)
}
func (m *PieUserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieUserListResponse.Marshal(b, m, deterministic)
}
func (m *PieUserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieUserListResponse.Merge(m, src)
}
func (m *PieUserListResponse) XXX_Size() int {
	return xxx_messageInfo_PieUserListResponse.Size(m)
}
func (m *PieUserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PieUserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PieUserListResponse proto.InternalMessageInfo

type PieUserAddRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieUserAddRequest) Reset()         { *m = PieUserAddRequest{} }
func (m *PieUserAddRequest) String() string { return proto.CompactTextString(m) }
func (*PieUserAddRequest) ProtoMessage()    {}
func (*PieUserAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{20}
}

func (m *PieUserAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieUserAddRequest.Unmarshal(m, b)
}
func (m *PieUserAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieUserAddRequest.Marshal(b, m, deterministic)
}
func (m *PieUserAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieUserAddRequest.Merge(m, src)
}
func (m *PieUserAddRequest) XXX_Size() int {
	return xxx_messageInfo_PieUserAddRequest.Size(m)
}
func (m *PieUserAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PieUserAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PieUserAddRequest proto.InternalMessageInfo

type PieUserAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieUserAddResponse) Reset()         { *m = PieUserAddResponse{} }
func (m *PieUserAddResponse) String() string { return proto.CompactTextString(m) }
func (*PieUserAddResponse) ProtoMessage()    {}
func (*PieUserAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{21}
}

func (m *PieUserAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieUserAddResponse.Unmarshal(m, b)
}
func (m *PieUserAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieUserAddResponse.Marshal(b, m, deterministic)
}
func (m *PieUserAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieUserAddResponse.Merge(m, src)
}
func (m *PieUserAddResponse) XXX_Size() int {
	return xxx_messageInfo_PieUserAddResponse.Size(m)
}
func (m *PieUserAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PieUserAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PieUserAddResponse proto.InternalMessageInfo

type PieUserRemoveRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieUserRemoveRequest) Reset()         { *m = PieUserRemoveRequest{} }
func (m *PieUserRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*PieUserRemoveRequest) ProtoMessage()    {}
func (*PieUserRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{22}
}

func (m *PieUserRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieUserRemoveRequest.Unmarshal(m, b)
}
func (m *PieUserRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieUserRemoveRequest.Marshal(b, m, deterministic)
}
func (m *PieUserRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieUserRemoveRequest.Merge(m, src)
}
func (m *PieUserRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_PieUserRemoveRequest.Size(m)
}
func (m *PieUserRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PieUserRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PieUserRemoveRequest proto.InternalMessageInfo

type PieUserRemoveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieUserRemoveResponse) Reset()         { *m = PieUserRemoveResponse{} }
func (m *PieUserRemoveResponse) String() string { return proto.CompactTextString(m) }
func (*PieUserRemoveResponse) ProtoMessage()    {}
func (*PieUserRemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{23}
}

func (m *PieUserRemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieUserRemoveResponse.Unmarshal(m, b)
}
func (m *PieUserRemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieUserRemoveResponse.Marshal(b, m, deterministic)
}
func (m *PieUserRemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieUserRemoveResponse.Merge(m, src)
}
func (m *PieUserRemoveResponse) XXX_Size() int {
	return xxx_messageInfo_PieUserRemoveResponse.Size(m)
}
func (m *PieUserRemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PieUserRemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PieUserRemoveResponse proto.InternalMessageInfo

type PieChunkListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieChunkListRequest) Reset()         { *m = PieChunkListRequest{} }
func (m *PieChunkListRequest) String() string { return proto.CompactTextString(m) }
func (*PieChunkListRequest) ProtoMessage()    {}
func (*PieChunkListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{24}
}

func (m *PieChunkListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieChunkListRequest.Unmarshal(m, b)
}
func (m *PieChunkListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieChunkListRequest.Marshal(b, m, deterministic)
}
func (m *PieChunkListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieChunkListRequest.Merge(m, src)
}
func (m *PieChunkListRequest) XXX_Size() int {
	return xxx_messageInfo_PieChunkListRequest.Size(m)
}
func (m *PieChunkListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PieChunkListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PieChunkListRequest proto.InternalMessageInfo

type PieChunkListResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieChunkListResponse) Reset()         { *m = PieChunkListResponse{} }
func (m *PieChunkListResponse) String() string { return proto.CompactTextString(m) }
func (*PieChunkListResponse) ProtoMessage()    {}
func (*PieChunkListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{25}
}

func (m *PieChunkListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieChunkListResponse.Unmarshal(m, b)
}
func (m *PieChunkListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieChunkListResponse.Marshal(b, m, deterministic)
}
func (m *PieChunkListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieChunkListResponse.Merge(m, src)
}
func (m *PieChunkListResponse) XXX_Size() int {
	return xxx_messageInfo_PieChunkListResponse.Size(m)
}
func (m *PieChunkListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PieChunkListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PieChunkListResponse proto.InternalMessageInfo

type PieChunkCreateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieChunkCreateRequest) Reset()         { *m = PieChunkCreateRequest{} }
func (m *PieChunkCreateRequest) String() string { return proto.CompactTextString(m) }
func (*PieChunkCreateRequest) ProtoMessage()    {}
func (*PieChunkCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{26}
}

func (m *PieChunkCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieChunkCreateRequest.Unmarshal(m, b)
}
func (m *PieChunkCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieChunkCreateRequest.Marshal(b, m, deterministic)
}
func (m *PieChunkCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieChunkCreateRequest.Merge(m, src)
}
func (m *PieChunkCreateRequest) XXX_Size() int {
	return xxx_messageInfo_PieChunkCreateRequest.Size(m)
}
func (m *PieChunkCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PieChunkCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PieChunkCreateRequest proto.InternalMessageInfo

type PieChunkCreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieChunkCreateResponse) Reset()         { *m = PieChunkCreateResponse{} }
func (m *PieChunkCreateResponse) String() string { return proto.CompactTextString(m) }
func (*PieChunkCreateResponse) ProtoMessage()    {}
func (*PieChunkCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{27}
}

func (m *PieChunkCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieChunkCreateResponse.Unmarshal(m, b)
}
func (m *PieChunkCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieChunkCreateResponse.Marshal(b, m, deterministic)
}
func (m *PieChunkCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieChunkCreateResponse.Merge(m, src)
}
func (m *PieChunkCreateResponse) XXX_Size() int {
	return xxx_messageInfo_PieChunkCreateResponse.Size(m)
}
func (m *PieChunkCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PieChunkCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PieChunkCreateResponse proto.InternalMessageInfo

type PieChunkApproveRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieChunkApproveRequest) Reset()         { *m = PieChunkApproveRequest{} }
func (m *PieChunkApproveRequest) String() string { return proto.CompactTextString(m) }
func (*PieChunkApproveRequest) ProtoMessage()    {}
func (*PieChunkApproveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{28}
}

func (m *PieChunkApproveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieChunkApproveRequest.Unmarshal(m, b)
}
func (m *PieChunkApproveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieChunkApproveRequest.Marshal(b, m, deterministic)
}
func (m *PieChunkApproveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieChunkApproveRequest.Merge(m, src)
}
func (m *PieChunkApproveRequest) XXX_Size() int {
	return xxx_messageInfo_PieChunkApproveRequest.Size(m)
}
func (m *PieChunkApproveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PieChunkApproveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PieChunkApproveRequest proto.InternalMessageInfo

type PieChunkApproveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieChunkApproveResponse) Reset()         { *m = PieChunkApproveResponse{} }
func (m *PieChunkApproveResponse) String() string { return proto.CompactTextString(m) }
func (*PieChunkApproveResponse) ProtoMessage()    {}
func (*PieChunkApproveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{29}
}

func (m *PieChunkApproveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieChunkApproveResponse.Unmarshal(m, b)
}
func (m *PieChunkApproveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieChunkApproveResponse.Marshal(b, m, deterministic)
}
func (m *PieChunkApproveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieChunkApproveResponse.Merge(m, src)
}
func (m *PieChunkApproveResponse) XXX_Size() int {
	return xxx_messageInfo_PieChunkApproveResponse.Size(m)
}
func (m *PieChunkApproveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PieChunkApproveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PieChunkApproveResponse proto.InternalMessageInfo

type PieChunkRejectRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieChunkRejectRequest) Reset()         { *m = PieChunkRejectRequest{} }
func (m *PieChunkRejectRequest) String() string { return proto.CompactTextString(m) }
func (*PieChunkRejectRequest) ProtoMessage()    {}
func (*PieChunkRejectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{30}
}

func (m *PieChunkRejectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieChunkRejectRequest.Unmarshal(m, b)
}
func (m *PieChunkRejectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieChunkRejectRequest.Marshal(b, m, deterministic)
}
func (m *PieChunkRejectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieChunkRejectRequest.Merge(m, src)
}
func (m *PieChunkRejectRequest) XXX_Size() int {
	return xxx_messageInfo_PieChunkRejectRequest.Size(m)
}
func (m *PieChunkRejectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PieChunkRejectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PieChunkRejectRequest proto.InternalMessageInfo

type PieChunkRejectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PieChunkRejectResponse) Reset()         { *m = PieChunkRejectResponse{} }
func (m *PieChunkRejectResponse) String() string { return proto.CompactTextString(m) }
func (*PieChunkRejectResponse) ProtoMessage()    {}
func (*PieChunkRejectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e350e21c42a6145, []int{31}
}

func (m *PieChunkRejectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PieChunkRejectResponse.Unmarshal(m, b)
}
func (m *PieChunkRejectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PieChunkRejectResponse.Marshal(b, m, deterministic)
}
func (m *PieChunkRejectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PieChunkRejectResponse.Merge(m, src)
}
func (m *PieChunkRejectResponse) XXX_Size() int {
	return xxx_messageInfo_PieChunkRejectResponse.Size(m)
}
func (m *PieChunkRejectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PieChunkRejectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PieChunkRejectResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SignInRequest)(nil), "dynamicequity.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "dynamicequity.SignInResponse")
	proto.RegisterType((*SignOutRequest)(nil), "dynamicequity.SignOutRequest")
	proto.RegisterType((*SignOutResponse)(nil), "dynamicequity.SignOutResponse")
	proto.RegisterType((*SignUpRequest)(nil), "dynamicequity.SignUpRequest")
	proto.RegisterType((*SignUpResponse)(nil), "dynamicequity.SignUpResponse")
	proto.RegisterType((*PieListRequest)(nil), "dynamicequity.PieListRequest")
	proto.RegisterType((*PieListResponse)(nil), "dynamicequity.PieListResponse")
	proto.RegisterType((*PieCreateRequest)(nil), "dynamicequity.PieCreateRequest")
	proto.RegisterType((*PieCreateResponse)(nil), "dynamicequity.PieCreateResponse")
	proto.RegisterType((*PieArchiveRequest)(nil), "dynamicequity.PieArchiveRequest")
	proto.RegisterType((*PieArchiveResponse)(nil), "dynamicequity.PieArchiveResponse")
	proto.RegisterType((*PieProjectListRequest)(nil), "dynamicequity.PieProjectListRequest")
	proto.RegisterType((*PieProjectListResponse)(nil), "dynamicequity.PieProjectListResponse")
	proto.RegisterType((*PieProjectAddRequest)(nil), "dynamicequity.PieProjectAddRequest")
	proto.RegisterType((*PieProjectAddResponse)(nil), "dynamicequity.PieProjectAddResponse")
	proto.RegisterType((*PieProjectArchiveRequest)(nil), "dynamicequity.PieProjectArchiveRequest")
	proto.RegisterType((*PieProjectArchiveResponse)(nil), "dynamicequity.PieProjectArchiveResponse")
	proto.RegisterType((*PieUserListRequest)(nil), "dynamicequity.PieUserListRequest")
	proto.RegisterType((*PieUserListResponse)(nil), "dynamicequity.PieUserListResponse")
	proto.RegisterType((*PieUserAddRequest)(nil), "dynamicequity.PieUserAddRequest")
	proto.RegisterType((*PieUserAddResponse)(nil), "dynamicequity.PieUserAddResponse")
	proto.RegisterType((*PieUserRemoveRequest)(nil), "dynamicequity.PieUserRemoveRequest")
	proto.RegisterType((*PieUserRemoveResponse)(nil), "dynamicequity.PieUserRemoveResponse")
	proto.RegisterType((*PieChunkListRequest)(nil), "dynamicequity.PieChunkListRequest")
	proto.RegisterType((*PieChunkListResponse)(nil), "dynamicequity.PieChunkListResponse")
	proto.RegisterType((*PieChunkCreateRequest)(nil), "dynamicequity.PieChunkCreateRequest")
	proto.RegisterType((*PieChunkCreateResponse)(nil), "dynamicequity.PieChunkCreateResponse")
	proto.RegisterType((*PieChunkApproveRequest)(nil), "dynamicequity.PieChunkApproveRequest")
	proto.RegisterType((*PieChunkApproveResponse)(nil), "dynamicequity.PieChunkApproveResponse")
	proto.RegisterType((*PieChunkRejectRequest)(nil), "dynamicequity.PieChunkRejectRequest")
	proto.RegisterType((*PieChunkRejectResponse)(nil), "dynamicequity.PieChunkRejectResponse")
}

func init() { proto.RegisterFile("proto/dynamicequity/service.proto", fileDescriptor_3e350e21c42a6145) }

var fileDescriptor_3e350e21c42a6145 = []byte{
	// 562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x56, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0x15, 0xa2, 0x4a, 0xcb, 0x40, 0x6f, 0xd3, 0xfb, 0x72, 0x4d, 0x5a, 0x2e, 0x4f, 0xa9, 0x54,
	0xbe, 0x20, 0xaa, 0x90, 0x40, 0x20, 0x30, 0x81, 0x08, 0x09, 0x89, 0x87, 0xe2, 0xac, 0xc8, 0x82,
	0x6a, 0xbb, 0xbe, 0x54, 0xca, 0xcf, 0xf2, 0x05, 0x7c, 0x04, 0xb2, 0x77, 0xec, 0xdd, 0xf1, 0xae,
	0x9d, 0xd7, 0x33, 0x67, 0xce, 0x1e, 0xef, 0xce, 0x1c, 0x19, 0x86, 0x49, 0x1a, 0xe7, 0xf1, 0xf9,
	0x7c, 0x19, 0x5d, 0x5d, 0xab, 0x50, 0xde, 0x14, 0x2a, 0x5f, 0x9e, 0x67, 0x32, 0xbd, 0x55, 0xa1,
	0x1c, 0x57, 0x35, 0xdc, 0x64, 0xc5, 0xd1, 0x36, 0x6c, 0x7e, 0x51, 0xbf, 0xa2, 0x77, 0xd1, 0x54,
	0xde, 0x14, 0x32, 0xcb, 0x47, 0x3b, 0xb0, 0x55, 0x03, 0x59, 0x12, 0x47, 0x99, 0xac, 0x91, 0x4f,
	0x45, 0x5e, 0x73, 0x76, 0x61, 0xbb, 0x41, 0x88, 0x44, 0x3a, 0xb3, 0xa4, 0xa5, 0x53, 0x02, 0x46,
	0x27, 0x50, 0xf2, 0x83, 0xca, 0x6c, 0x9d, 0x06, 0x21, 0x12, 0xc2, 0x4e, 0xa0, 0xe4, 0x65, 0x2a,
	0xaf, 0x72, 0x59, 0xd3, 0xf6, 0x60, 0xd7, 0xc2, 0x88, 0xa8, 0xc1, 0x49, 0x1a, 0x2e, 0xd4, 0x6d,
	0xc3, 0xdc, 0x07, 0xb4, 0x41, 0xa2, 0x1e, 0xc1, 0x41, 0xa0, 0x64, 0x90, 0xc6, 0xbf, 0x65, 0x98,
	0xdb, 0xe7, 0x1f, 0xc3, 0x61, 0xbb, 0x40, 0x2d, 0x87, 0xb0, 0x6f, 0x2a, 0x93, 0xf9, 0xbc, 0xee,
	0x60, 0x52, 0x15, 0x4e, 0x0d, 0x02, 0x8e, 0xad, 0x02, 0x77, 0xf5, 0x10, 0x4e, 0x3c, 0x35, 0x6a,
	0xd4, 0x96, 0x67, 0x99, 0x4c, 0x6d, 0x67, 0x07, 0xb0, 0xc7, 0x50, 0xf6, 0xd1, 0x25, 0x6c, 0x79,
	0x32, 0x0a, 0xb6, 0x21, 0xfd, 0x05, 0x25, 0x3a, 0x95, 0xd7, 0xb1, 0x31, 0xa3, 0xbf, 0xc0, 0xc6,
	0xa9, 0x41, 0x1f, 0x79, 0xb9, 0x28, 0xa2, 0x3f, 0xb6, 0x13, 0xad, 0x63, 0xc1, 0xec, 0x52, 0x2b,
	0x9c, 0xbf, 0x96, 0xbe, 0x54, 0x56, 0xa0, 0x16, 0xab, 0x32, 0x49, 0x92, 0xd4, 0x32, 0x75, 0x02,
	0x47, 0x4e, 0xc5, 0x3d, 0x67, 0x2a, 0xcb, 0x0b, 0xf4, 0x9c, 0x53, 0x17, 0x74, 0xcb, 0xc5, 0xdf,
	0x3b, 0xb0, 0x36, 0x29, 0xf2, 0x05, 0xbe, 0x81, 0x81, 0x9e, 0x65, 0x7c, 0x34, 0x66, 0x63, 0x3f,
	0x66, 0x33, 0x2f, 0x1e, 0x77, 0x54, 0xb5, 0x1e, 0xbe, 0x85, 0x75, 0x1a, 0x77, 0xf4, 0x31, 0xcd,
	0x62, 0x88, 0x27, 0x5d, 0x65, 0x52, 0x22, 0x43, 0xb3, 0xc4, 0x6b, 0xa8, 0x59, 0x1e, 0xaf, 0x21,
	0xb3, 0x49, 0x17, 0xff, 0x36, 0xe0, 0x6e, 0xa0, 0x4a, 0xb9, 0xb5, 0xf2, 0x4d, 0x1c, 0x57, 0x7c,
	0xcd, 0x1c, 0x57, 0xad, 0x9d, 0xc3, 0xf7, 0x30, 0xd0, 0x2f, 0x85, 0x4f, 0x5d, 0x26, 0x7b, 0x5c,
	0xf1, 0xac, 0x9b, 0x40, 0x62, 0x1f, 0x61, 0x9d, 0x46, 0x1c, 0x3d, 0x64, 0xbe, 0x19, 0x62, 0xd8,
	0xc3, 0x20, 0xbd, 0xef, 0x70, 0xdf, 0x5a, 0x50, 0x3c, 0x73, 0x3b, 0xdc, 0xc5, 0x16, 0xcf, 0x57,
	0xb0, 0x48, 0xfb, 0x1b, 0x80, 0x59, 0x65, 0x3c, 0xed, 0x6c, 0x32, 0xcb, 0x26, 0xce, 0xfa, 0x49,
	0x24, 0x1c, 0xc2, 0x16, 0x5f, 0x77, 0x7c, 0xd9, 0xdd, 0xc7, 0xaf, 0xe4, 0xd5, 0x6a, 0x22, 0x1d,
	0xf2, 0x19, 0x36, 0xea, 0x80, 0x40, 0xcf, 0x45, 0xb6, 0x22, 0x45, 0x8c, 0xfa, 0x28, 0xe6, 0xf1,
	0x28, 0x47, 0x7c, 0x8f, 0xc7, 0x73, 0x47, 0x0c, 0x7b, 0x18, 0xe6, 0x82, 0x4d, 0xd2, 0xf8, 0x2e,
	0xd8, 0xc9, 0x27, 0xdf, 0x05, 0xbb, 0x61, 0x85, 0x5f, 0xe1, 0x5e, 0x13, 0x49, 0xe8, 0xf9, 0xb2,
	0x76, 0x8c, 0x89, 0xd3, 0x5e, 0x8e, 0x99, 0x35, 0x2b, 0xb7, 0x7c, 0xb3, 0xe6, 0xe6, 0x9d, 0x6f,
	0xd6, 0x3c, 0xe1, 0x87, 0x3f, 0xe0, 0x81, 0x9d, 0x6f, 0xd8, 0xd5, 0xc6, 0x93, 0x51, 0xbc, 0x58,
	0x45, 0x6b, 0x59, 0xd7, 0x51, 0xd8, 0x69, 0x9d, 0x45, 0x68, 0xa7, 0x75, 0x9e, 0xa7, 0x3f, 0x07,
	0xd5, 0x9f, 0xc3, 0xeb, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x65, 0xa7, 0xe5, 0x5e, 0x08,
	0x00, 0x00,
}
