// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

var TableNames = struct {
	Chunks           string
	Pies             string
	PiesUsers        string
	Projects         string
	Roles            string
	SchemaMigrations string
	Users            string
	UsersRoles       string
}{
	Chunks:           "chunks",
	Pies:             "pies",
	PiesUsers:        "pies_users",
	Projects:         "projects",
	Roles:            "roles",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
	UsersRoles:       "users_roles",
}
