// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testChunks(t *testing.T) {
	t.Parallel()

	query := Chunks()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testChunksDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Chunk{}
	if err = randomize.Struct(seed, o, chunkDBTypes, true, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Chunks().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testChunksQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Chunk{}
	if err = randomize.Struct(seed, o, chunkDBTypes, true, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Chunks().DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Chunks().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testChunksSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Chunk{}
	if err = randomize.Struct(seed, o, chunkDBTypes, true, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ChunkSlice{o}

	if rowsAff, err := slice.DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Chunks().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testChunksExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Chunk{}
	if err = randomize.Struct(seed, o, chunkDBTypes, true, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ChunkExists(tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Chunk exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ChunkExists to return true, but got false.")
	}
}

func testChunksFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Chunk{}
	if err = randomize.Struct(seed, o, chunkDBTypes, true, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	chunkFound, err := FindChunk(tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if chunkFound == nil {
		t.Error("want a record, got nil")
	}
}

func testChunksBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Chunk{}
	if err = randomize.Struct(seed, o, chunkDBTypes, true, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Chunks().Bind(nil, tx, o); err != nil {
		t.Error(err)
	}
}

func testChunksOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Chunk{}
	if err = randomize.Struct(seed, o, chunkDBTypes, true, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Chunks().One(tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testChunksAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	chunkOne := &Chunk{}
	chunkTwo := &Chunk{}
	if err = randomize.Struct(seed, chunkOne, chunkDBTypes, false, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}
	if err = randomize.Struct(seed, chunkTwo, chunkDBTypes, false, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = chunkOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = chunkTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Chunks().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testChunksCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	chunkOne := &Chunk{}
	chunkTwo := &Chunk{}
	if err = randomize.Struct(seed, chunkOne, chunkDBTypes, false, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}
	if err = randomize.Struct(seed, chunkTwo, chunkDBTypes, false, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = chunkOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = chunkTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Chunks().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func chunkBeforeInsertHook(e boil.Executor, o *Chunk) error {
	*o = Chunk{}
	return nil
}

func chunkAfterInsertHook(e boil.Executor, o *Chunk) error {
	*o = Chunk{}
	return nil
}

func chunkAfterSelectHook(e boil.Executor, o *Chunk) error {
	*o = Chunk{}
	return nil
}

func chunkBeforeUpdateHook(e boil.Executor, o *Chunk) error {
	*o = Chunk{}
	return nil
}

func chunkAfterUpdateHook(e boil.Executor, o *Chunk) error {
	*o = Chunk{}
	return nil
}

func chunkBeforeDeleteHook(e boil.Executor, o *Chunk) error {
	*o = Chunk{}
	return nil
}

func chunkAfterDeleteHook(e boil.Executor, o *Chunk) error {
	*o = Chunk{}
	return nil
}

func chunkBeforeUpsertHook(e boil.Executor, o *Chunk) error {
	*o = Chunk{}
	return nil
}

func chunkAfterUpsertHook(e boil.Executor, o *Chunk) error {
	*o = Chunk{}
	return nil
}

func testChunksHooks(t *testing.T) {
	t.Parallel()

	var err error

	empty := &Chunk{}
	o := &Chunk{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, chunkDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Chunk object: %s", err)
	}

	AddChunkHook(boil.BeforeInsertHook, chunkBeforeInsertHook)
	if err = o.doBeforeInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	chunkBeforeInsertHooks = []ChunkHook{}

	AddChunkHook(boil.AfterInsertHook, chunkAfterInsertHook)
	if err = o.doAfterInsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	chunkAfterInsertHooks = []ChunkHook{}

	AddChunkHook(boil.AfterSelectHook, chunkAfterSelectHook)
	if err = o.doAfterSelectHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	chunkAfterSelectHooks = []ChunkHook{}

	AddChunkHook(boil.BeforeUpdateHook, chunkBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	chunkBeforeUpdateHooks = []ChunkHook{}

	AddChunkHook(boil.AfterUpdateHook, chunkAfterUpdateHook)
	if err = o.doAfterUpdateHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	chunkAfterUpdateHooks = []ChunkHook{}

	AddChunkHook(boil.BeforeDeleteHook, chunkBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	chunkBeforeDeleteHooks = []ChunkHook{}

	AddChunkHook(boil.AfterDeleteHook, chunkAfterDeleteHook)
	if err = o.doAfterDeleteHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	chunkAfterDeleteHooks = []ChunkHook{}

	AddChunkHook(boil.BeforeUpsertHook, chunkBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	chunkBeforeUpsertHooks = []ChunkHook{}

	AddChunkHook(boil.AfterUpsertHook, chunkAfterUpsertHook)
	if err = o.doAfterUpsertHooks(nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	chunkAfterUpsertHooks = []ChunkHook{}
}

func testChunksInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Chunk{}
	if err = randomize.Struct(seed, o, chunkDBTypes, true, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Chunks().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testChunksInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Chunk{}
	if err = randomize.Struct(seed, o, chunkDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Whitelist(chunkColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Chunks().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testChunkToOneUserUsingUser(t *testing.T) {

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var local Chunk
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, chunkDBTypes, false, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := ChunkSlice{&local}
	if err = local.L.LoadUser(tx, false, (*[]*Chunk)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testChunkToOnePieUsingPie(t *testing.T) {

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var local Chunk
	var foreign Pie

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, chunkDBTypes, true, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, pieDBTypes, false, pieColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Pie struct: %s", err)
	}

	if err := foreign.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.PieID, foreign.ID)
	if err := local.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Pie().One(tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := ChunkSlice{&local}
	if err = local.L.LoadPie(tx, false, (*[]*Chunk)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Pie == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Pie = nil
	if err = local.L.LoadPie(tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Pie == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testChunkToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a Chunk
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, chunkDBTypes, false, strmangle.SetComplement(chunkPrimaryKeyColumns, chunkColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Chunks[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}
func testChunkToOneSetOpPieUsingPie(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a Chunk
	var b, c Pie

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, chunkDBTypes, false, strmangle.SetComplement(chunkPrimaryKeyColumns, chunkColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, pieDBTypes, false, strmangle.SetComplement(piePrimaryKeyColumns, pieColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, pieDBTypes, false, strmangle.SetComplement(piePrimaryKeyColumns, pieColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Pie{&b, &c} {
		err = a.SetPie(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Pie != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.PieChunks[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.PieID, x.ID) {
			t.Error("foreign key was wrong value", a.PieID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.PieID))
		reflect.Indirect(reflect.ValueOf(&a.PieID)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.PieID, x.ID) {
			t.Error("foreign key was wrong value", a.PieID, x.ID)
		}
	}
}

func testChunkToOneRemoveOpPieUsingPie(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a Chunk
	var b Pie

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, chunkDBTypes, false, strmangle.SetComplement(chunkPrimaryKeyColumns, chunkColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, pieDBTypes, false, strmangle.SetComplement(piePrimaryKeyColumns, pieColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetPie(tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemovePie(tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Pie().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Pie != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.PieID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.PieChunks) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testChunksReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Chunk{}
	if err = randomize.Struct(seed, o, chunkDBTypes, true, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testChunksReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Chunk{}
	if err = randomize.Struct(seed, o, chunkDBTypes, true, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ChunkSlice{o}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}

func testChunksSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Chunk{}
	if err = randomize.Struct(seed, o, chunkDBTypes, true, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Chunks().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	chunkDBTypes = map[string]string{`ID`: `integer`, `UserID`: `integer`, `PieID`: `integer`, `Amount`: `integer`, `Approved`: `boolean`, `Archived`: `boolean`, `Comment`: `text`}
	_            = bytes.MinRead
)

func testChunksUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(chunkPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(chunkColumns) == len(chunkPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Chunk{}
	if err = randomize.Struct(seed, o, chunkDBTypes, true, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Chunks().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, chunkDBTypes, true, chunkPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	if rowsAff, err := o.Update(tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testChunksSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(chunkColumns) == len(chunkPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Chunk{}
	if err = randomize.Struct(seed, o, chunkDBTypes, true, chunkColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Chunks().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, chunkDBTypes, true, chunkPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(chunkColumns, chunkPrimaryKeyColumns) {
		fields = chunkColumns
	} else {
		fields = strmangle.SetComplement(
			chunkColumns,
			chunkPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ChunkSlice{o}
	if rowsAff, err := slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testChunksUpsert(t *testing.T) {
	t.Parallel()

	if len(chunkColumns) == len(chunkPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Chunk{}
	if err = randomize.Struct(seed, &o, chunkDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Chunk: %s", err)
	}

	count, err := Chunks().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, chunkDBTypes, false, chunkPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Chunk struct: %s", err)
	}

	if err = o.Upsert(tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Chunk: %s", err)
	}

	count, err = Chunks().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
