// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Chunks", testChunksUpsert)

	t.Run("Pies", testPiesUpsert)

	t.Run("Projects", testProjectsUpsert)

	t.Run("Roles", testRolesUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)

	t.Run("Users", testUsersUpsert)
}
